Add back text matrices for taking banner screenshots
wmde/fundraising-banners pull request #151
Opened 2023-07-17 10:20 UTC by moiikana

- the test matrices are taken from the old banner repo (2022)

2023-07-20 16:31 UTC, gbirke requested changes

2023-07-20 16:31 UTC, gbirke commented on campaign_info.toml
> +platform = ["edge", "ie11", "firefox_win10", "chrome_win10", "safari", "firefox_macos", "chrome_macos", "firefox_linux", "chrome_linux"]
Our new banners no longer support ie11 :relieved:

2023-07-24 06:20 UTC, Abban approved these changes

2023-07-24 08:24 UTC, gbirke approved these changes

2023-07-25 13:29 UTC, merged