C24_WMDE_Mobile_DE_03
wmde/fundraising-banners pull request #506
Opened 2024-08-05 14:28 UTC by Sperling-0

- The banners are based on the CTRL banner of desktop-de-02

Ticket: https://phabricator.wikimedia.org/T371476

2024-08-06 06:52 UTC, Abban commented on banners/desktop/C24_WMDE_Desktop_DE_03/styles/styles.scss
> +@use 'src/themes/Treedip/DonationForm/Forms/UpgradeToYearlyButtonForm' with (
Oops, wrong theme

2024-08-06 06:52 UTC, Abban commented on banners/thank_you/components/ProgressBar.vue
> -const props = defineProps<Props>();
Looks like this change sneaked in

2024-08-09 11:14 UTC, Abban requested changes
It's mostly perfect, I spotted some unused things that could be moved or deleted.

You imported the wrong theme files for the bubble forms, you should import the Svingle ones and copy the css changes you made in Treedip to there without using variables. Then revert the Treedip changes.

2024-08-09 11:14 UTC, Abban commented on banners/desktop/C24_WMDE_Desktop_DE_03/currentCampaignTimePercentage.ts
> +export function currentCampaignTimePercentage( date: Date, campaignParameters: CampaignParameters ): number {
This is for the double progress bar and isn't being used in the banners currently. I think it can be moved into `src/components/ProgressBar`

2024-08-09 11:14 UTC, Abban commented on banners/desktop/C24_WMDE_Desktop_DE_03/messages.ts
> +const messages: TranslationMessages = {
We should remove the messages that aren't being used from here. The extra ones at the bottom could also be moved into the component messages.

2024-08-09 11:14 UTC, Abban commented on banners/desktop/C24_WMDE_Desktop_DE_03/styles/MainBanner.scss
> +$padding-top: 10px !default;
These are banner specific styles so you can remove these 3 variables and inline the values.

2024-08-09 11:14 UTC, Abban commented on src/themes/Treedip/DonationForm/BubbleForm/SelectCustomAmountRadioBubble.scss
> +$border-radius: 8px !default;
These could also be removed and the values put inline.

2024-08-09 11:14 UTC, Abban commented on banners/desktop/C24_WMDE_Desktop_DE_03/styles/stylesVar.scss
> +@use 'src/themes/Treedip/DonationForm/BubbleForm/SelectGroupBubble' with (
These imports are pointing to the wrong theme.

2024-08-13 09:54 UTC, Sperling-0 commented on banners/desktop/C24_WMDE_Desktop_DE_03/styles/MainBanner.scss
> +$padding-top: 10px !default;
Are you sure about this? I feel we need variables here. But I did the changes as you requested.

2024-08-15 08:38 UTC, Abban approved these changes

2024-08-15 08:39 UTC, merged