C24_WMDE_Mobile_DE_05
wmde/fundraising-banners pull request #556
Opened 2024-09-30 11:44 UTC by moiikana

- based on de 04 ctrl
- var has additional "thank you" text box

https://phabricator.wikimedia.org/T374103

2024-10-01 13:59 UTC, Abban requested changes
It all looks pretty good, but I'm hitting request changes to remind us to talk about the colour variables in the daily tomorrow.

2024-10-01 13:59 UTC, Abban commented on src/components/ThankYouBox/ThankYouBox.scss
> +		height: 60px;
The height in the design is 40px

2024-10-01 13:59 UTC, Abban commented on src/themes/Mikings/ThankYouBox/ThankYouBox.scss
> +		background: #ebe2fc;
This is another thing we should create color variables for, and a flag I think.

But it also has me thinking, what do we do if they want to test 2 different colours of the box? We should chat about it in the daily tomorrow.

2024-10-01 13:59 UTC, Abban commented on src/components/Icons/HeartIcon.vue
> +	<svg width="16" height="16" viewBox="0 0 16 16" fill="#6b4ba1" xmlns="http://www.w3.org/2000/svg">
When you put the colours into the swatch you can remove `fill="#6b4ba1"` and add `style="var( --thank-you-heart-fill )"`

2024-10-02 10:56 UTC, moiikana commented on src/components/ThankYouBox/ThankYouBox.scss
> +		height: 60px;
the design in the figma file is overall a bit different to our actual current live banners.
In figma, both, submit button and thank you box are 40px high.
In our live banners, the submit button has a height of 60px though.
That's why I assume I should keep them the same height (60px).

2024-10-02 11:30 UTC, Abban commented on src/components/ThankYouBox/ThankYouBox.scss
> +		height: 60px;
Ah right, grand so!

2024-10-02 11:30 UTC, Abban approved these changes

2024-10-07 10:57 UTC, moiikana commented
(rebased because of package-lock file)

2024-10-08 07:58 UTC, merged