Inline UoF infographics and Icons into Fundraising Banners
wmde/fundraising-banners pull request #563
Opened 2024-10-02 07:50 UTC by Sperling-0

- Add Infografics and Icon svgs as Vue components
    
    - No banners should include images that are hosted on Wikimedia Commons
    - No banners should include images that are coming from `fundraising-frontend-content` repo

Ticket: https://phabricator.wikimedia.org/T375848

2024-10-08 08:01 UTC, gbirke approved these changes

2024-10-10 11:05 UTC, moiikana commented
on previous banners the use of funds graphics (info graphic and close icon) looked like this:
![Bildschirmfoto vom 2024-10-10 13-03-06](https://github.com/user-attachments/assets/edc56e6b-8a8c-4cbf-9972-59025da386c5)


currently in this PR it looks like this:
![Bildschirmfoto vom 2024-10-10 13-03-18](https://github.com/user-attachments/assets/6df6f3b4-c1d1-4146-b2f0-f7df03b0e640)
1) there used to be some centering/spacing for the info graphic
2) the close icon needs a white background, so it's still well readable when it's floating over text

2024-10-10 11:06 UTC, moiikana requested changes
(see comment above)

2024-10-16 05:59 UTC, Abban requested changes
It's nearly there.

I spotted an issue with the swatching, where the css variable for the close button background isn't being properly set. You need to make a couple of changes to fix it:

1. Change line 2 in `src/components/UseOfFunds/FundsModal.vue` to

```html
<div :class="[ 'banner-modal funds-modal', { 'is-visible': isFundsModalVisible } ]">
```

2. Cange the selectors in `src/themes/UseOfFunds/swatches/skin_default.scss` and `src/themes/UseOfFunds/swatches/skin_vector-2022.scss` from `.use-of-funds` to `.funds-modal`.

2024-10-16 05:59 UTC, Abban commented on src/themes/UseOfFunds/FundsContent.scss
> +		text-align: center;
We need to keep the padding here:

```suggestion
		text-align: center;
		padding: 0 50px;
```

2024-10-16 05:59 UTC, Abban commented on src/components/UseOfFunds/Icons/IconClose.vue
> +	<svg width="32" height="32" viewBox="0 0 32 32" fill="#ffffff" xmlns="http://www.w3.org/2000/svg">
This needs to respect dark mode so we remove the fill and make sure it has a background in css using my suggestions in the main comment:

```suggestion
	<svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
```

2024-10-17 07:25 UTC, Abban approved these changes

2024-10-17 15:54 UTC, moiikana commented
close button looks good now :+1: 
while checking I noticed that on the **desktop fallback banner** (<- only appears on very small screens on (refresh the page))
and on the **de mobile banner** the infographic in the UoF is missing.
![Bildschirmfoto vom 2024-10-17 17-48-04](https://github.com/user-attachments/assets/5db35ca7-f203-45c0-bdab-6fda8220cd99)

2024-10-18 11:22 UTC, Sperling-0 commented
> close button looks good now 👍 while checking I noticed that
> 
>     * on the **desktop fallback banner** (<- only appears on very small screens on (refresh the page))
>       ![Bildschirmfoto vom 2024-10-17 17-48-04](https://private-user-images.githubusercontent.com/11670701/377541541-5db35ca7-f203-45c0-bdab-6fda8220cd99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNDYxNTYsIm5iZiI6MTcyOTI0NTg1NiwicGF0aCI6Ii8xMTY3MDcwMS8zNzc1NDE1NDEtNWRiMzVjYTctZjIwMy00NWMwLWJkYWItNmZkYTgyMjBjZDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDEwMDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYzNlMThhNjllYjlmMTA1MWIwN2JlZTdhOWI3YjhmY2U4MzFmNTk0MmEzMTIwZjdlNzVjZDk4ODFjNTk5YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iNoMDXMgNaNFfEIoQIHGFhek8P-JzJrtsVWSbi06QAE)
> 
>     * and on the **de mobile banner**
>       the infographic in the UoF is missing.

Now, these issues have been fixed. I re-based this PR from/to main.

2024-10-18 11:36 UTC, moiikana approved these changes

2024-10-18 11:36 UTC, merged