C24_WMDE_Mobile_DE_09
wmde/fundraising-banners pull request #624
Opened 2024-11-15 14:01 UTC by moiikana

based on 08 VAR
var has 10 reasons popup

https://phabricator.wikimedia.org/T379953

2024-11-18 17:10 UTC, gbirke requested changes

2024-11-18 17:10 UTC, gbirke commented on banners/mobile/C24_WMDE_Mobile_DE_09/MinimisedTracker.ts
> + * I'm leaving it here in case it gets re-added while I'm away.
Please delete this file and all other files related to minimisation - those files were not cleaned up in test 08 because it might not have been clear which banner wins when test09 was created. But since the minimize feature does not seem to come back, let's remove unused files in this test.

2024-11-18 17:10 UTC, gbirke commented on banners/mobile/C24_WMDE_Mobile_DE_09/styles/MiniBanner_var.scss
> +		margin-bottom: 0 !important;
`!important` should be the last, desparate tool you reach for after you have intensively tried out deeper and deeper selector specificity. In this case, I recommend moving the selector into the `.wmde-banner-mini` section above it, and omitting the `&` and using `.wmde-banner-slide-reasons-to-donate-sentence`

2024-11-18 17:10 UTC, gbirke commented on src/components/ReasonsToDonate/ReasonsToDonate.vue
> -			<button @click="$emit( 'hide' )">
I like the simpler event names that don't repeat the component name in them, they'll be easier to read in the template. But that's just my personal taste.

2024-11-18 17:10 UTC, gbirke commented on test/features/ReasonsToDonate.ts
> +	console.log( wrapper.html() );
Please remove this `console.log` when the test passes

2024-11-18 17:10 UTC, gbirke commented on test/features/ReasonsToDonate.ts
> +	expect( tracker.trackEvent ).toHaveBeenCalledTimes( 2 );
The test should only expect 1.
This is probably due to the removal of the tracking on the "close" event inside the `ReasonsToDonate` component

2024-11-19 09:01 UTC, Abban requested changes
Some suggestions for fixing the tests

2024-11-19 09:01 UTC, Abban commented on src/components/ReasonsToDonate/ReasonsToDonate.vue
> -			<button @click="$emit( 'hide' )">
I see that you're trying to make this more consistent with the Use of Funds, but I'd prefer if this component fired different events for the close and CTA click, as this removes the need for an enum, and the requirement for an if branch in all the banner components.

2024-11-19 09:01 UTC, Abban commented on test/features/ReasonsToDonate.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
You can remove this and the second parameter from the function. When the later parameters aren't used, js doesn't care if the signature is different from the interface. Wild west typing.

2024-11-19 09:01 UTC, Abban commented on test/features/ReasonsToDonate.ts
> +	await wrapper.find( '.wmde-banner-10-reasons-cta' ).trigger( 'click' );
```suggestion
	await wrapper.find( '.wmde-banner-10-reasons-cta button' ).trigger( 'click' );
```

2024-11-19 09:01 UTC, Abban commented on test/features/ReasonsToDonate.ts
> +	expect( tracker.trackEvent ).toHaveBeenCalledTimes( 2 );
The tracker (with the CTA button selector fix) fires 3 calls when the CTA is clicked:

- Open the dialog
- CTA click
- Mini banner expanded

We should probably not fire the last one, as we can assume the CTA event that we're tracking opens the main banner.

2024-11-19 09:01 UTC, Abban commented on test/features/ReasonsToDonate.ts
> +	await wrapper.find( '.wmde-banner-10-reasons-accordion-item' ).trigger( 'click' );
There's an example of what you need to do in the `ReasonsToDonate.spec.ts` tests
```suggestion
	wait wrapper.find( '.wmde-banner-10-reasons-accordion-item:nth-child(1) .wmde-banner-10-reasons-accordion-title' ).trigger( 'click' );
	await wrapper.find( '.wmde-banner-10-reasons-accordion-item:nth-child(8) .wmde-banner-10-reasons-accordion-title' ).trigger( 'click' );
```

Then check the nth-child number is passed to the event as it's close choice.

2024-11-19 10:46 UTC, Abban commented on test/features/ReasonsToDonate.ts
> +	await nextTick();
You might not need to await the nextTick in these as the action caused by the button click should be performed in the previous one.

2024-11-19 12:01 UTC, moiikana commented on src/components/ReasonsToDonate/ReasonsToDonate.vue
> -			<button @click="$emit( 'hide' )">
> I like the simpler event names that don't repeat the component name in them, they'll be easier to read in the template. But that's just my personal taste.

I hope I understood your point, but if we e.g. have 3 popup features that all send "hide" to the parent, 
I feared that the browser / DOM event handling could be messing up which event came from which component.

2024-11-19 12:20 UTC, moiikana commented on test/features/ReasonsToDonate.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
nice, I thought the linter didn't like it yesterday

2024-11-19 13:24 UTC, Abban commented
I created a follow up PR that adds explicit styles for the links in the content, and swaps the links to buttons https://github.com/wmde/fundraising-banners/pull/626

2024-11-20 14:15 UTC, gbirke approved these changes

2024-11-21 13:27 UTC, Abban approved these changes

2024-11-21 13:27 UTC, Abban commented on banners/mobile/C24_WMDE_Mobile_DE_09/content/BannerSlides_var.vue
> +				id="reasons-to-donate-link"
You can remove this id, it's appearing on the page twice

2024-11-21 13:27 UTC, Abban commented on banners/mobile/C24_WMDE_Mobile_DE_09/content/BannerSlides_var.vue
> +				class="wmde-banner-reasons-to-donate-link t-reasons-to-donate-link"
```suggestion
				class="wmde-banner-reasons-to-donate-link"
```

2024-11-21 13:27 UTC, Abban commented on src/components/ReasonsToDonate/ReasonsToDonate.vue
> -			<button @click="$emit( 'hide' )">
Vue emits aren't generic browser events, and it binds the handlers directly (eg `@hide="doThisThing"`). So 3 components can all emit "hide" events, and as long as they're bound to different functions it'll be okay.

2024-11-21 13:27 UTC, merged