Fix Fallback Banner for EN Desktop
wmde/fundraising-banners pull request #661
Opened 2024-12-12 17:08 UTC by gbirke

Test 06 introduced a border in the main banner which now needs to be overwritten in the Fallback banner since they share class names

2024-12-12 17:09 UTC, gbirke commented
Already deployed to CN

2024-12-12 17:10 UTC, moiikana commented
Ticket: https://phabricator.wikimedia.org/T382001

2024-12-13 14:47 UTC, moiikana requested changes
this change causes the ctrl banner to not have any border anymore
![Bildschirmfoto vom 2024-12-13 15-46-26](https://github.com/user-attachments/assets/45228cdf-f8b1-467c-98ae-ec456bb2ae43)

2024-12-19 18:05 UTC, gbirke commented
Thank you for testing this so thoroughly and catching my silly mistakes!
I'll close this PR and won't fix the mistake (which would involve adding `Fallback_var.scss` to Desktop EN 06), because:
1. The banner will be replaced with (correct) the VAR tomorrow
2. Is unlikely to be revived.

I've created #675 to address the root cause of all the fallback banner problems in the cleanup.

2024-12-19 18:05 UTC, closed without merging